#!/usr/bin/env python3
from pathlib import Path
import json
R=Path(__file__).resolve().parents[4]
checks=[]
def ok(name,cond): assert cond,name; checks.append(name)
rev=json.loads((R/'knowledge_base/paper_reviews/2024-E-S019-core.json').read_text(encoding='utf-8'))
ok('S019 full review',rev['review_status'].startswith('FULL_TEXT'))
ok('S019 60 pages',rev['pages']==60)
ok('S019 train split',rev['split']=='train')
ok('S019 Q1-Q4',set(rev['questions'])=={'Q1','Q2','Q3','Q4'})
ok('S019 algebra inverse risk',any('Eq.(32)' in x and 'Eq.(33)' in x for x in rev['questions']['Q1']['risks']))
ok('S019 unit contract risk',any('q=u*rho' in x and '1/60' in x for x in rev['questions']['Q1']['risks']))
ok('S019 regression row replay risk',any('21940' in x and '311' in x for x in rev['questions']['Q1']['risks']))
ok('S019 threshold result drift',any('2700' in x and '300' in x for x in rev['questions']['Q1']['risks']))
ok('S019 temporal split risk',any('chronologically' in x or 'random' in x for x in rev['questions']['Q1']['risks']))
ok('S019 importance causal boundary',any('predictive evidence' in x.lower() and 'causal' in x.lower() for x in rev['questions']['Q1']['risks']))
ok('S019 density unit drift',any('veh/m' in x and 'veh/km' in x for x in rev['questions']['Q1']['risks']))
ok('S019 hysteresis route',any('0.8' in x and '0.6' in x for x in rev['questions']['Q2']['route']))
ok('S019 qmax calibration risk',any('Qmax' in x or 'Qmax' in x.replace('_','') for x in rev['questions']['Q2']['risks']))
ok('S019 30pct scenario risk',any(('30%' in x) or ('1.3' in x and 'scenario' in x.lower()) for x in rev['questions']['Q3']['risks']))
ok('S019 sign reversal risk',any('Eq.(52)' in x and 'Eq.(53)' in x for x in rev['questions']['Q3']['risks']))
ok('S019 heuristic placement risk',any('heuristic' in x.lower() for x in rev['questions']['Q4']['risks']))
code=json.loads((R/'knowledge_base/code_cases/2024-E-S019-appendix-code.json').read_text(encoding='utf-8'))
ok('S019 appendix list only',code['run_status'].startswith('APPENDIX_FILE_LIST_ONLY'))
ok('S019 appendix 16 artifacts',len(code['listed_artifacts'])>=12)
ok('S019 no source split audit',any('cannot be audited' in x for x in code['questions']['Q1']['findings']))
ok('S019 no placement optimization code',any('No optimization program' in x for x in code['questions']['Q4']['findings']))
sm=json.loads((R/'learning_output/analyses/v123_S019/contract_audit_smoke.json').read_text(encoding='utf-8'))['checks']
ok('S019 smoke traffic unit mismatch',sm['traffic_unit_contract']['contract_consistent'] is False)
ok('S019 smoke algebra inverse',sm['eq32_inverse']['equivalent_to_eq32'] is False and sm['eq32_inverse']['correct_inverse_tau_min']<sm['eq32_inverse']['reported_table10_min_duration_min'])
ok('S019 smoke regression mismatch',sm['linear_regression_replay']['magnitude_consistent'] is False and sm['linear_regression_replay']['replayed_prediction']>20000)
ok('S019 smoke threshold drift',sm['threshold_result_drift']['A_consistent'] is False and sm['threshold_result_drift']['B_consistent'] is False)
ok('S019 smoke qmax mismatch',sm['qmax_replay']['same_definition_consistent'] is False)
ok('S019 smoke 48.3 replay valid',sm['duration_percentage_replay']['consistent_with_rounding'] is True)
ok('S019 smoke inventory sign mismatch',sm['inventory_sign_contract']['sign_consistent'] is False)
ok('S019 smoke scenario only',sm['intervention_evidence']['observed_treatment_data'] is False)
ok('S019 smoke policy weights unvalidated',sm['policy_weight_provenance']['fitted_or_sensitivity_validated'] is False)
ok('S019 smoke sensor dependency break',sm['sensor_policy_dependency']['old_policy_reusable_without_recalibration'] is False)
ok('S019 smoke appendix unavailable',sm['appendix_source_availability']['source_bodies_found_in_current_worktree']==0)
ok('S019 smoke split provenance incomplete',sm['forecast_split_provenance']['time_forecast_validation_complete'] is False)
fig=json.loads((R/'knowledge_base/figure_argumentation/S019.json').read_text(encoding='utf-8'))
ok('S019 52 figures',fig['figure_count_indexed']==52)
ok('S019 11 tables',fig['table_count_indexed']==11)
ok('S019 no pixel overclaim','not mounted original S019 PDF pixels' in fig['style_learning_boundary'])
for rel in fig['derived_template_smoke']: ok(rel,(R/rel).exists() and (R/rel).stat().st_size>5000)
for fn in ['derived-equation-algebra-mismatch.json','regression-equation-scale-impossibility.json','cross-table-timestamp-drift.json','assumed-capacity-multiplier-as-intervention-evidence.json','heuristic-sensor-relocation-without-optimization.json']:
    ok(fn,(R/'knowledge_base/error_patterns'/fn).exists())
cross=json.loads((R/'knowledge_base/cross_paper_maps/2024-E-S017-S020.json').read_text(encoding='utf-8'))
ok('2024-E S017-S019 preserved',all(x in cross['papers_reviewed'] for x in ['S017','S018','S019']))
ok('2024-E map still contains S020','S020' in cross['papers'])
ok('cross has S019 Q1', 'S019' in cross['questions']['Q1'])
papers=json.loads((R/'.agents/skills/mathmodel-case-retriever/assets/papers.json').read_text(encoding='utf-8'))
p19=next(x for x in papers if x['paper_id']=='S019')
ok('S019 registry reviewed',p19['reviewed_pages']==list(range(1,61)))
ok('S019 asset links',all(k in p19 for k in ['review_file','code_audit_file','figure_argumentation_file']))
for pid in ['S013','S014','S015','S016']:
    pp=next(x for x in papers if x['paper_id']==pid); ok(pid+' remains dev split',pp.get('split')=='dev')
for pid in ['S021','S022','S023','S024','S037','S038']:
    pp=next(x for x in papers if x['paper_id']==pid); ok(pid+' test remains unread',pp.get('split')=='test' and pp.get('reviewed_pages',[])==[])
p20=next(x for x in papers if x['paper_id']=='S020')
ok('S020 remains train',p20['split']=='train')
ref=R/'.agents/skills/graduate-mathmodel-learning/references/2024-E-S019-paper-code-audit.md'
ok('S019 audit reference',ref.exists() and ref.stat().st_size>2000)
skill=(R/'.agents/skills/graduate-mathmodel-learning/SKILL.md').read_text(encoding='utf-8')
ok('v1.23 gates in skill','v1.23：公式反解、回归尺度与情景干预证据门禁' in skill)
sel=(R/'.agents/skills/modeling-paper-rubric-and-model-selector/SKILL.md').read_text(encoding='utf-8')
ok('v1.23 selector gates','公式回放、控制状态与情景干预闸门（v1.23）' in sel)
state=json.loads((R/'learning_output/context/learning_state.json').read_text(encoding='utf-8'))
ok('S019 history preserved',any('S019' in x for x in state.get('completed_papers',[]) or []) or 'S019' in json.dumps(state,ensure_ascii=False))
ok('version >=1.23',tuple(map(int,(R/'VERSION').read_text().strip().split('.')[:2])) >= (1,23))
print(json.dumps({'status':'PASS','scope':'v1.23 S019 algebra/regression/control/intervention/layout audit','passed':len(checks),'tests':checks},ensure_ascii=False,indent=2))
