#!/usr/bin/env python3
from pathlib import Path
import json
R=Path(__file__).resolve().parents[4]
checks=[]
def ok(name,cond): assert cond,name; checks.append(name)
rev=json.loads((R/'knowledge_base/paper_reviews/2024-E-S018-core.json').read_text(encoding='utf-8'))
ok('S018 full review',rev['review_status'].startswith('FULL_TEXT'))
ok('S018 81 pages',rev['pages']==81)
ok('S018 train split',rev['split']=='train')
ok('S018 Q1-Q4',set(rev['questions'])=={'Q1','Q2','Q3','Q4'})
ok('S018 10x timebase risk',any('10×' in x or '10x' in x.lower() for x in rev['questions']['Q1']['risks']))
ok('S018 25 vs 33 aggregation',any('33' in x and '25' in x for x in rev['questions']['Q1']['risks']))
ok('S018 temporal count density risk',any('spatial' in x.lower() and 'density' in x.lower() for x in rev['questions']['Q1']['risks']))
ok('S018 single timestep risk',any('one timestep' in x.lower() for x in rev['questions']['Q1']['risks']))
ok('S018 undefined attention W',any('undefined w' in x.lower() for x in rev['questions']['Q1']['risks']))
ok('S018 metric algebra risk',any('0.1652' in x and '0.2164' in x for x in rev['questions']['Q1']['risks']))
ok('S018 warning code drift',any('0.85' in x and '1.3' in x for x in rev['questions']['Q1']['risks']))
ok('S018 threshold boolean drift',any('OR' in x and 'AND' in x for x in rev['questions']['Q2']['risks']))
ok('S018 threshold timebase risk',any('timebase' in x.lower() for x in rev['questions']['Q2']['risks']))
ok('S018 transportability risk',any('transportability' in x.lower() for x in rev['questions']['Q3']['risks']))
ok('S018 metric semantic risk',any('Eq.(47)' in x or 'T_ET/N_TC' in x for x in rev['questions']['Q3']['risks']))
ok('S018 speed percent replay risk',any('129.53' in x and '58.25' in x for x in rev['questions']['Q3']['risks']))
ok('S018 q4 variable mismatch',any('decision variable' in x.lower() and 'camera' in x.lower() for x in rev['questions']['Q4']['risks']))
ok('S018 q4 normalization weights missing',any('normalization' in x.lower() and 'weights' in x.lower() for x in rev['questions']['Q4']['risks']))
ok('S018 surrogate validation risk',any('surrogate' in x.lower() and ('error' in x.lower() or 'valid' in x.lower()) for x in rev['questions']['Q4']['risks']))
code=json.loads((R/'knowledge_base/code_cases/2024-E-S018-appendix-code.json').read_text(encoding='utf-8'))
ok('S018 static replay honest',code['run_status'].startswith('STATIC_AUDIT'))
ok('S018 Q1 visible fragments',len(code['questions']['Q1']['visible_fragments'])>=3)
ok('S018 Q2 appendix mismatch',any('Mask-RCNN' in x for x in code['questions']['Q2']['findings']))
ok('S018 Q3 no complete executable',any('no complete executable' in x.lower() for x in code['questions']['Q3']['findings']))
ok('S018 Q4 no Kriging GA code',any('Kriging' in x and 'GA' in x for x in code['questions']['Q4']['findings']))
sm=json.loads((R/'learning_output/analyses/v122_S018/contract_audit_smoke.json').read_text(encoding='utf-8'))['checks']
ok('S018 smoke 25 vs33',sm['frame_timebase_contract']['contract_consistent'] is False)
ok('S018 smoke 10x real time',sm['real_video_timebase']['real_seconds_per_25_frames']==10.0 and sm['real_video_timebase']['real_seconds_per_33_frames']==13.2)
ok('S018 smoke warning drift',sm['warning_rule_contract']['consistent'] is False and sm['warning_rule_contract']['paper_gradient_threshold']==1.3 and sm['warning_rule_contract']['printed_code_gradient_threshold']==0.85)
ok('S018 smoke metric point3 valid',sm['metric_algebra']['obs3']['consistent'] is True)
ok('S018 smoke metric point4 invalid',sm['metric_algebra']['obs4']['consistent'] is False)
ok('S018 smoke percentage replay',sm['percentage_replay']['video1_speed']['standard_before_denominator_percent']>120)
ok('S018 smoke sequence length1',sm['forecast_architecture_visibility']['printed_bigru_sequence_length']==1)
ok('S018 smoke appendix mismatch',sm['appendix_relevance']['Q2'].startswith('mismatched'))
ok('S018 smoke decision variable mismatch',sm['q4_decision_variable_contract']['matches'] is False)
ok('S018 smoke Eq47 semantics',sm['metric_semantic_contract']['semantic_match'] is False)
ok('S018 smoke q4 scalarization not replayable',sm['q4_scalarization_contract']['normalization_formula_visible'] is False and sm['q4_scalarization_contract']['numeric_weights_visible'] is False)
fig=json.loads((R/'knowledge_base/figure_argumentation/S018.json').read_text(encoding='utf-8'))
ok('S018 53 figures',fig['figure_count_indexed']==53)
ok('S018 10 tables',fig['table_count_indexed']==10)
ok('S018 no pixel overclaim','not mounted original S018 PDF pixels' in fig['style_learning_boundary'])
for rel in fig['derived_template_smoke']: ok(rel,(R/rel).exists() and (R/rel).stat().st_size>5000)
for fn in ['frame-aggregation-paper-code-mismatch.json','temporal-count-spatial-density-confusion.json','threshold-boolean-policy-drift.json','percentage-change-denominator-error.json','appendix-section-method-mismatch.json','optimization-variable-task-mismatch.json','sensor-placement-benefit-mediation-gap.json','accelerated-video-timebase-unit-drift.json','metric-formula-variable-semantic-mismatch.json','cross-site-counterfactual-transportability-gap.json','surrogate-optimizer-without-surrogate-validation.json']:
    ok(fn,(R/'knowledge_base/error_patterns'/fn).exists())
cross=json.loads((R/'knowledge_base/cross_paper_maps/2024-E-S017-S020.json').read_text(encoding='utf-8'))
ok('2024-E S017 S018 reviewed',all(x in cross['papers_reviewed'] for x in ['S017','S018']))
ok('2024-E S017 S018 preserved',all(x in cross['papers_reviewed'] for x in ['S017','S018']))
papers=json.loads((R/'.agents/skills/mathmodel-case-retriever/assets/papers.json').read_text(encoding='utf-8'))
p18=next(x for x in papers if x['paper_id']=='S018')
ok('S018 registry reviewed',p18['reviewed_pages']==list(range(1,82)))
ok('S018 asset links',all(k in p18 for k in ['review_file','code_audit_file','figure_argumentation_file']))
for pid in ['S013','S014','S015','S016']:
    pp=next(x for x in papers if x['paper_id']==pid); ok(pid+' remains dev split',pp.get('split')=='dev')
for pid in ['S021','S022','S023','S024','S037','S038']:
    pp=next(x for x in papers if x['paper_id']==pid); ok(pid+' test remains unread',pp.get('split')=='test' and pp.get('reviewed_pages',[])==[])
p20=next(x for x in papers if x['paper_id']=='S020'); ok('S020 stays train',p20['split']=='train')
ref=R/'.agents/skills/graduate-mathmodel-learning/references/2024-E-S018-paper-code-audit.md'
ok('S018 audit reference',ref.exists() and ref.stat().st_size>3000)
skill=(R/'.agents/skills/graduate-mathmodel-learning/SKILL.md').read_text(encoding='utf-8')
ok('v1.22 gates in skill','v1.22：帧时间基准、阈值状态机与优化变量契约门禁' in skill)
sel=(R/'.agents/skills/modeling-paper-rubric-and-model-selector/SKILL.md').read_text(encoding='utf-8')
ok('v1.22 selector gates','交通视频、阈值策略与布点优化闸门（v1.22）' in sel)
state=json.loads((R/'learning_output/context/learning_state.json').read_text(encoding='utf-8'))
ok('learning state advanced past S018',state['current_focus']['session_id'].startswith('v1.'))
ok('version >=1.22',tuple(map(int,(R/'VERSION').read_text().strip().split('.')[:2])) >= (1,22))
print(json.dumps({'status':'PASS','scope':'v1.22 S018 frame/time/metric/threshold/intervention/placement audit','passed':len(checks),'tests':checks},ensure_ascii=False,indent=2))
