#!/usr/bin/env python3
from pathlib import Path
import json
R=Path(__file__).resolve().parents[4]
checks=[]
def ok(name,cond): assert cond,name; checks.append(name)
rev=json.loads((R/'knowledge_base/paper_reviews/2024-E-S017-core.json').read_text(encoding='utf-8'))
ok('S017 full review',rev['review_status'].startswith('FULL_TEXT'))
ok('S017 84 pages',rev['pages']==84)
ok('S017 train split',rev['split']=='train')
ok('S017 Q1-Q4',set(rev['questions'])=={'Q1','Q2','Q3','Q4'})
ok('S017 temporal leakage identified',any('overlapping' in x.lower() and 'split' in x.lower() for x in rev['questions']['Q1']['risks']))
ok('S017 relative density calibration risk',any('relative' in x.lower() and ('vehicles/km' in x.lower() or 'physical' in x.lower()) for x in rev['questions']['Q1']['risks']))
ok('S017 Greenberg parameter mismatch',any('130' in x and '120' in x for x in rev['questions']['Q1']['risks']))
ok('S017 prediction plot alignment risk',any('time-aligned' in x.lower() or 'chronological' in x.lower() for x in rev['questions']['Q1']['risks']))
ok('S017 LSTM implementation not visible',any('lstm' in x.lower() and 'no ' in x.lower() for x in rev['questions']['Q1']['risks']))
ok('S017 selected positive validation risk',any('two predicted' in x.lower() or 'selected-positive' in x.lower() for x in rev['questions']['Q1']['risks']))
ok('S017 association intervention risk',any('correlation' in x.lower() and ('intervention' in x.lower() or 'causal' in x.lower()) for x in rev['questions']['Q2']['risks']))
ok('S017 multipliers as assumptions',any('multiplying' in x.lower() and 'assumptions' in x.lower() for x in rev['questions']['Q3']['risks']))
ok('S017 Q4 dimensional risk',any('dimensionally inconsistent' in x.lower() for x in rev['questions']['Q4']['risks']))
code=json.loads((R/'knowledge_base/code_cases/2024-E-S017-appendix-code.json').read_text(encoding='utf-8'))
ok('S017 static-only run honest',code['run_status'].startswith('STATIC_AUDIT_ONLY'))
ok('S017 visible CV code',any('YOLOv5' in x for x in code['questions']['Q1']['visible_fragments']))
ok('S017 no visible LSTM code',any('no visible LSTM' in x for x in code['questions']['Q1']['findings']))
ok('S017 hard path dependencies', 'hard-coded' in code['questions']['Q1']['runability'])
sm=json.loads((R/'learning_output/analyses/v121_S017/contract_audit_smoke.json').read_text(encoding='utf-8'))['checks']
ok('S017 paper/code Greenberg mismatch smoke',sm['greenberg_parameter_contract']['paper_free_speed_kmh']==130 and sm['greenberg_parameter_contract']['printed_code_V_c_kmh']==120)
ok('S017 density unit not verified',sm['greenberg_parameter_contract']['density_input_physical_unit_verified'] is False)
ok('S017 window split leakage smoke',sm['temporal_split_contract']['overlap_possible_across_train_test'] is True)
ok('S017 plot alignment smoke',sm['prediction_plot_alignment']['chronological_alignment_preserved'] is False)
ok('S017 selected event validation smoke',sm['selected_event_validation']['selected_positive_checks']==2 and sm['selected_event_validation']['full_event_confusion_metrics_visible'] is False)
ok('S017 multiplier not treatment estimate',sm['intervention_effect_contract']['estimated_from_observed_treatment'] is False)
ok('S017 LSTM visibility false',sm['appendix_implementation_visibility']['LSTM_training'] is False)
fig=json.loads((R/'knowledge_base/figure_argumentation/S017.json').read_text(encoding='utf-8'))
ok('S017 48 figure ids',fig['figure_count_indexed']==48)
ok('S017 6 table ids',fig['table_count_indexed']==6)
ok('S017 no pixel overclaim','not mounted original S017 PDF pixels' in fig['style_learning_boundary'])
for rel in fig['derived_template_smoke']: ok(rel,(R/rel).exists() and (R/rel).stat().st_size>5000)
for fn in ['proxy-to-physical-calibration-mismatch.json','selected-positive-examples-validation.json','association-to-intervention-overclaim.json','dimensionally-inconsistent-state-update.json','assumed-treatment-multiplier-as-evidence.json']:
    ok(fn,(R/'knowledge_base/error_patterns'/fn).exists())
cross=json.loads((R/'knowledge_base/cross_paper_maps/2024-E-S017-S020.json').read_text(encoding='utf-8'))
ok('2024-E map four papers',cross['papers']==['S017','S018','S019','S020'])
ok('2024-E S017 remains reviewed','S017' in cross['papers_reviewed'])
ok('2024-E S020 remains train','S020' in cross['papers'] and next(x for x in json.loads((R/'.agents/skills/mathmodel-case-retriever/assets/papers.json').read_text(encoding='utf-8')) if x['paper_id']=='S020')['split']=='train')
papers=json.loads((R/'.agents/skills/mathmodel-case-retriever/assets/papers.json').read_text(encoding='utf-8'))
p=next(x for x in papers if x['paper_id']=='S017')
ok('S017 registry train',p['split']=='train')
ok('S017 all pages reviewed',p['reviewed_pages']==list(range(1,85)))
ok('S017 asset links',all(k in p for k in ['review_file','code_audit_file','figure_argumentation_file']))
# legal-timepoint adaptation: Dev may be reviewed later; Test must remain unread.
for pid in ['S013','S014','S015','S016']:
    pp=next(x for x in papers if x['paper_id']==pid); ok(pid+' remains dev split',pp.get('split')=='dev')
for pid in ['S021','S022','S023','S024','S037','S038']:
    pp=next(x for x in papers if x['paper_id']==pid); ok(pid+' test remains unread',pp.get('split')=='test' and pp.get('reviewed_pages',[])==[])
mapg=json.loads((R/'.agents/skills/mathmodel-case-retriever/assets/case_group_maps.json').read_text(encoding='utf-8'))
ok('2024-E retrieval map registered',mapg['2024-E']['cross_paper_map']=='knowledge_base/cross_paper_maps/2024-E-S017-S020.json')
skill=(R/'.agents/skills/graduate-mathmodel-learning/SKILL.md').read_text(encoding='utf-8')
ok('v1.21 gates in skill','v1.21：时序窗口、物理标定与干预证据门禁' in skill)
sel=(R/'.agents/skills/modeling-paper-rubric-and-model-selector/SKILL.md').read_text(encoding='utf-8')
ok('v1.21 selector gates','时序、物理单位与干预决策闸门（v1.21）' in sel)
state=json.loads((R/'learning_output/context/learning_state.json').read_text(encoding='utf-8'))
ok('learning state has advanced beyond v1.21',state['current_focus']['session_id'].startswith('v1.'))
ok('S017 history preserved',any('S017' in x for x in state.get('pending_replications',[])))
ok('version >=1.21',tuple(map(int,(R/'VERSION').read_text().strip().split('.')[:2])) >= (1,21))
print(json.dumps({'status':'PASS','scope':'v1.21 S017 traffic time/unit/intervention audit','passed':len(checks),'tests':checks},ensure_ascii=False,indent=2))
