#!/usr/bin/env python3
from pathlib import Path
import json
R=Path(__file__).resolve().parents[4]
checks=[]
def ok(name, cond):
    assert cond, name; checks.append(name)
rev=json.loads((R/'knowledge_base/paper_reviews/2024-C-S011-core.json').read_text(encoding='utf-8'))
ok('S011 full review',rev['review_status'].startswith('FULL_TEXT'))
ok('S011 71 pages',rev['pages']==71)
ok('S011 Q1-Q5',set(rev['questions'])=={'Q1','Q2','Q3','Q4','Q5'})
ok('S011 Q1 nested screening risk',any('nested' in x.lower() or 'inside each cv fold' in x.lower() for x in rev['questions']['Q1']['risks']))
ok('S011 Q2 holdout risk',any('held-out' in x.lower() or 'same temperature support' in x.lower() for x in rev['questions']['Q2']['risks']))
ok('S011 Q3 crosstab not interaction',any('interaction term' in x.lower() or '协同' in x for x in rev['questions']['Q3']['risks']))
ok('S011 Q4 architecture mismatch',any('no lstm' in x.lower() or 'cnnmodel' in x.lower() for x in rev['questions']['Q4']['risks']))
ok('S011 Q4 feature dim mismatch',any('1033' in x and '10' in x for x in rev['questions']['Q4']['risks']))
ok('S011 Q4 perturbation not generalization',any('perturbation' in x.lower() and 'generalization' in x.lower() for x in rev['questions']['Q4']['risks']))
ok('S011 Q5 endogenous preference',any('weight a' in x.lower() and 'decision variable' in x.lower() for x in rev['questions']['Q5']['risks']))
ok('S011 Q5 infeasible Bm',any('0.4261' in x for x in rev['questions']['Q5']['risks']))
ok('S011 Q5 infeasible f',any('49910' in x for x in rev['questions']['Q5']['risks']))
ok('S011 Q5 no code',any('no ga/pso' in x.lower() or 'no q5' in x.lower() or 'no q5' in x.lower() for x in rev['questions']['Q5']['risks']))
ok('S011 Pareto concentration warning',any('concentrated' in x.lower() or 'hypervolume' in x.lower() for x in rev['questions']['Q5']['risks']))
code=json.loads((R/'knowledge_base/code_cases/2024-C-S011-appendix-code.json').read_text(encoding='utf-8'))
ok('S011 partial run honest',code['run_status'].startswith('PARTIAL'))
ok('S011 code Q1-Q5',set(code['questions'])=={'Q1','Q2','Q3','Q4','Q5'})
ok('S011 smoke linked',code['smoke_report']=='learning_output/analyses/v119_S011/q4_q5_contract_smoke.json')
smoke=json.loads((R/code['smoke_report']).read_text(encoding='utf-8'))
ok('S011 printed no LSTM',smoke['q4']['lstm_layer_visible'] is False)
ok('S011 1033 vs 10 mismatch',smoke['q4']['feature_contract_match'] is False and smoke['q4']['printed_claimed_model_input_size']==1033)
ok('S011 two infeasible reported MOPSO',len(smoke['q5']['reported_mopso_examples'])==2 and all(not x['feasible'] for x in smoke['q5']['reported_mopso_examples']))
ok('S011 raw scalarization mismatch',all(not x['matches'] for x in smoke['q5']['scalarization_replay']))
ok('S011 Q5 implementation absent',smoke['q5']['printed_q5_implementation_visible'] is False)
fig=json.loads((R/'knowledge_base/figure_argumentation/S011.json').read_text(encoding='utf-8'))
ok('S011 43 figure ids',fig['explicit_caption_count']==43)
ok('S011 28 table ids',fig['table_caption_count']==28)
ok('S011 no pixel overclaim',fig['pixel_level_audit'] is False)
for fn in ['descriptive-crosstab-not-interaction.json','architecture-name-implementation-mismatch.json','perturbation-robustness-not-generalization.json','endogenous-preference-weight.json','pareto-visual-concentration-quality-overclaim.json','test-statistic-pvalue-confusion.json']:
    ok(fn,(R/'knowledge_base/error_patterns'/fn).exists())
cross=json.loads((R/'knowledge_base/cross_paper_maps/2024-C-S009-S012.json').read_text(encoding='utf-8'))
ok('S009 S010 S011 historical reviews retained',set(['S009','S010','S011']).issubset(set(cross['papers_reviewed'])))
ok('S012 remains in 2024-C map and may progress', 'S012' in cross['papers'])
ok('S011 included all Q',all('S011' in cross['questions'][q] for q in ['Q1','Q2','Q3','Q4','Q5']))
papers=json.loads((R/'.agents/skills/mathmodel-case-retriever/assets/papers.json').read_text(encoding='utf-8'))
p=next(x for x in papers if x['paper_id']=='S011')
ok('S011 remains train',p['split']=='train')
ok('S011 all pages reviewed',p['reviewed_pages']==list(range(1,72)))
ok('S011 links review/code/figure',all(k in p for k in ['review_file','code_audit_file','figure_argumentation_file']))
ref=R/'.agents/skills/graduate-mathmodel-learning/references/2024-C-S011-paper-code-audit.md'
ok('S011 audit reference',ref.exists() and ref.stat().st_size>2500)
skill=(R/'.agents/skills/graduate-mathmodel-learning/SKILL.md').read_text(encoding='utf-8')
ok('v1.19 gates in skill','v1.19：交互证据、架构真实性与 Pareto 可行性门禁' in skill)
sel=(R/'.agents/skills/modeling-paper-rubric-and-model-selector/SKILL.md').read_text(encoding='utf-8')
ok('v1.19 selector gates','交互、架构与 Pareto 真实性闸门（v1.19）' in sel)
for rel in ['learning_output/analyses/v119_figure_template_smoke/01_interaction_evidence.png','learning_output/analyses/v119_figure_template_smoke/02_pareto_feasibility.png']:
    ok(rel,(R/rel).exists() and (R/rel).stat().st_size>5000)
ver=tuple(map(int,(R/'VERSION').read_text().strip().split('.')[:2])); ok('version >=1.19',ver>=(1,19))
print(json.dumps({'status':'PASS','scope':'v1.19 S011 full-text printed-appendix architecture/Pareto audit','passed':len(checks),'tests':checks},ensure_ascii=False,indent=2))
