#!/usr/bin/env python3
from pathlib import Path
import json
R=Path(__file__).resolve().parents[4]
checks=[]
def ok(name,cond):
    assert cond,name; checks.append(name)
rev=json.loads((R/'knowledge_base/paper_reviews/2024-C-S012-core.json').read_text(encoding='utf-8'))
ok('S012 full review',rev['review_status'].startswith('FULL_TEXT'))
ok('S012 105 pages',rev['pages']==105)
ok('S012 train split',rev['split']=='train')
ok('S012 Q1-Q5',set(rev['questions'])=={'Q1','Q2','Q3','Q4','Q5'})
ok('S012 Q1 scaling leakage',any('before train/validation split' in x.lower() or 'before train/validation' in x.lower() for x in rev['questions']['Q1']['risks']))
ok('S012 Q2 leave-condition risk',any('leave-temperature' in x.lower() or 'unseen-temperature' in x.lower() for x in rev['questions']['Q2']['risks']))
ok('S012 Q3 intercept F transcription',any('3456.213' in x and '17.755' in x for x in rev['questions']['Q3']['risks']))
ok('S012 Q3 F not effect size',any('not effect sizes' in x.lower() or 'effect size' in x.lower() for x in rev['questions']['Q3']['risks']))
ok('S012 Q3 multiple testing',any('47' in x and ('family' in x.lower() or 'fdr' in x.lower()) for x in rev['questions']['Q3']['risks']))
ok('S012 Q3 order dependence',any('order-dependent' in x.lower() for x in rev['questions']['Q3']['risks']))
ok('S012 Q4 implementation evidence',any('embeddings' in x.lower() or 'embedding' in x.lower() for x in rev['questions']['Q4']['strengths']))
ok('S012 Q4 grouped generalization risk',any('leave-material' in x.lower() or 'cross-material' in x.lower() for x in rev['questions']['Q4']['risks']))
ok('S012 Q5 bound drift',any('50000' in x and '5000' in x for x in rev['questions']['Q5']['risks']))
ok('S012 Q5 mixed discrete risk',any('discrete' in x.lower() and 'continuous' in x.lower() for x in rev['questions']['Q5']['risks']))
ok('S012 Q5 lambda replay',any('lambda=10' in x.lower() and 'lambda=100' in x.lower() for x in rev['questions']['Q5']['risks']))
code=json.loads((R/'knowledge_base/code_cases/2024-C-S012-appendix-code.json').read_text(encoding='utf-8'))
ok('S012 partial run honest',code['run_status'].startswith('PARTIAL'))
ok('S012 code Q1-Q5',set(code['questions'])=={'Q1','Q2','Q3','Q4','Q5'})
ok('S012 smoke linked',code['smoke_report']=='learning_output/analyses/v120_S012/contract_replay_smoke.json')
smoke=json.loads((R/code['smoke_report']).read_text(encoding='utf-8'))
ok('S012 paper f lower 50000',smoke['q5']['paper_frequency_bounds'][0]==50000)
ok('S012 code f lower 5000',smoke['q5']['ga_code_frequency_bounds'][0]==5000 and smoke['q5']['pso_code_frequency_bounds'][0]==5000)
ok('S012 reported lambda1 point infeasible',smoke['q5']['paper_reported_pso_lambda_1_feasible_under_paper_bounds'] is False)
ok('S012 lambda 10/100 swapped by replay',smoke['q5']['lambda_10_100_rows_appear_swapped_by_formula'] is True)
ok('S012 printed lambda selects 100',smoke['q5']['printed_lambda_value']==100)
ok('S012 explicit interaction visible',smoke['q3']['explicit_interaction_model_visible'] is True)
ok('S012 F transcription smoke',smoke['q3']['temperature_table_F']==17.755 and smoke['q3']['temperature_prose_F_mistakenly_uses_intercept']==3456.213)
ok('S012 no multiplicity correction',smoke['q3']['sequential_mann_whitney_tests']==47 and smoke['q3']['multiplicity_correction_visible'] is False)
fig=json.loads((R/'knowledge_base/figure_argumentation/S012.json').read_text(encoding='utf-8'))
ok('S012 27 canonical figures',fig['explicit_unique_figure_id_count']==27)
ok('S012 38 tables',fig['explicit_unique_table_id_count']==38)
ok('S012 no pixel overclaim',fig['pixel_level_audit'] is False)
for rel in fig['derived_template_smoke']:
    ok(rel,(R/rel).exists() and (R/rel).stat().st_size>5000)
for fn in ['f-statistic-as-effect-size.json','multiple-testing-without-correction.json','sequential-pairwise-tournament-order-dependence.json','mixed-variable-continuous-relaxation.json','domain-registry-paper-code-bound-drift.json','scalarized-objective-table-replay-failure.json']:
    ok(fn,(R/'knowledge_base/error_patterns'/fn).exists())
cross=json.loads((R/'knowledge_base/cross_paper_maps/2024-C-S009-S012.json').read_text(encoding='utf-8'))
ok('2024-C all four reviewed',cross['papers_reviewed']==['S009','S010','S011','S012'])
ok('2024-C no pending',cross['papers_pending']==[])
ok('S012 included all Q',all('S012' in cross['questions'][q] for q in ['Q1','Q2','Q3','Q4','Q5']))
papers=json.loads((R/'.agents/skills/mathmodel-case-retriever/assets/papers.json').read_text(encoding='utf-8'))
p=next(x for x in papers if x['paper_id']=='S012')
ok('S012 remains train registry',p['split']=='train')
ok('S012 all pages reviewed',p['reviewed_pages']==list(range(1,106)))
ok('S012 links review/code/figure',all(k in p for k in ['review_file','code_audit_file','figure_argumentation_file']))
# legal-timepoint adaptation: Dev may have been reviewed later; split must remain Dev. Test remains unread.
for pid in ['S013','S014','S015','S016']:
    pp=next(x for x in papers if x['paper_id']==pid)
    ok(pid+' remains dev split',pp.get('split')=='dev')
for pid in ['S021','S022','S023','S024','S037','S038']:
    pp=next(x for x in papers if x['paper_id']==pid)
    ok(pid+' test remains unread',pp.get('split')=='test' and pp.get('reviewed_pages',[])==[])
ref=R/'.agents/skills/graduate-mathmodel-learning/references/2024-C-S012-paper-code-audit.md'
ok('S012 audit reference',ref.exists() and ref.stat().st_size>2500)
skill=(R/'.agents/skills/graduate-mathmodel-learning/SKILL.md').read_text(encoding='utf-8')
ok('v1.20 gates in skill','v1.20：效应量、多重比较、混合变量与目标复算门禁' in skill)
sel=(R/'.agents/skills/modeling-paper-rubric-and-model-selector/SKILL.md').read_text(encoding='utf-8')
ok('v1.20 selector gates','效应量、多重比较与混合优化真实性闸门（v1.20）' in sel)
state=json.loads((R/'learning_output/context/learning_state.json').read_text(encoding='utf-8'))
ok('S017 progressed or remains next', any('S017' in x for x in state.get('next_actions',[])) or next(x for x in papers if x['paper_id']=='S017').get('reviewed_pages',[])==list(range(1,85)))
ok('dev S013-S016 lifecycle',all(next(x for x in papers if x['paper_id']==pid).get('split')=='dev' for pid in ['S013','S014','S015','S016']))
ok('version >=1.20',tuple(map(int,(R/'VERSION').read_text().strip().split('.')[:2])) >= (1,20))
print(json.dumps({'status':'PASS','scope':'v1.20 S012 full-text printed-appendix effect/mixed-optimization audit','passed':len(checks),'tests':checks},ensure_ascii=False,indent=2))
