"""Local bounded Q1/Q2 timing ablations, Q4 formula reconstruction, table statistics.
Our reimplementations; neither original MATLAB nor a full author-code replay.
"""
from pathlib import Path
import random,math,json,re,statistics,hashlib,sys
HERE=Path(__file__).resolve().parent;CASE=HERE.parents[1];ROOT=CASE.parents[2]
sys.path.insert(0,str(CASE/'code'))
from analytic import q2_exact
from q3_state_model import state_terms

def epochs(q,extra_time,extra_decrement,seed,count=100000):
    rng=random.Random(seed);rate=455.8 if q==1 else 275.3
    d=13.6+12240/rate;counter=[rng.randrange(16),rng.randrange(16)]
    stage=[0,0];success=[0,0];t=43.;collisions=0
    for _ in range(count):
        low=min(counter);senders=[i for i in range(2) if counter[i]==low]
        fail=q==1 and len(senders)==2
        t+=9*(low+extra_time)+d+(108 if fail else 91)
        if fail:collisions+=1
        for i in range(2):
            if i in senders:
                if not fail:success[i]+=1
                stage[i]=stage[i]+1 if fail and stage[i]<32 else 0
                counter[i]=rng.randrange(min(1024,16*2**stage[i]))
            else:
                counter[i]-=low+extra_decrement
                assert counter[i]>=0
    return dict(seed=seed,total_mbps=sum(success)*12000/t,
                twice_ap1_mbps=2*success[0]*12000/t,success=success,elapsed_us=t,collisions=collisions)

def q4(rate=455.8,w=16,cap=1024,r=32,omit_failed_terms=False):
    def terms(f1):
        a=state_terms(f1,rate,w,cap,r)
        ov=a['overlap']+(a['no_overlap_terms'][2]+a['no_overlap_terms'][3] if omit_failed_terms else 0)
        f2=a['tau']*(2-ov);b=state_terms(f2,rate,w,cap,r)
        return f1-b['tau'],a,b,ov,f2
    lo,hi=0.,1.
    assert terms(lo)[0]<0<terms(hi)[0]
    for _ in range(70):
        mid=(lo+hi)/2
        if terms(mid)[0]>0:hi=mid
        else:lo=mid
    f1=(lo+hi)/2;res,a,b,ov,f2=terms(f1);t1=a['tau'];t2=b['tau']
    den=(t1*(1-f1)+t2*(1-f2))*a['Ts']+t2*f2*a['Tc']+(1-t2-t1*(1-f1))*9
    per=[12000*t1*(1-f1)/den,12000*t2*(1-f2)/den,12000*t1*(1-f1)/den]
    assert abs(res)<1e-12 and 0<=ov<=1 and 0<=f2<=1
    return dict(total_mbps=sum(per),per_node_mbps=per,outer_failure=f1,center_failure=f2,
                overlap=ov,outer_tau=t1,center_tau=t2,residual=res,omit_failed_terms=omit_failed_terms)

def main():
    ablations=[]
    for q in [1,2]:
        for extra_time,extra_decrement in [(0,0),(1,0),(0,1),(1,1)]:
            runs=[epochs(q,extra_time,extra_decrement,s) for s in [101,202,303,404,505]]
            mean=statistics.mean(r['total_mbps'] for r in runs)
            ablations.append(dict(q=q,extra_time_slots=extra_time,extra_decrement=extra_decrement,
                total_mean=mean,seed_sd=statistics.stdev(r['total_mbps'] for r in runs),runs=runs))
            print(q,extra_time,extra_decrement,mean,flush=True)
    base=json.loads((CASE/'results/RESULTS.json').read_text(encoding='utf-8'))
    q4rows=[]
    for b in base:
        if b['question']!=4:continue
        p=b['params'];args=dict(rate=p.get('rate',455.8),w=p.get('cwmin',16),cap=p.get('cwmax',1024),r=p.get('retries',32))
        body=q4(**args);appendix=q4(**args,omit_failed_terms=True)
        q4rows.append(dict(id=b['id'],params=args,body=body,appendix_active=appendix,
                          frozen_simulation_mbps=b['total_mean'],body_relative_error=body['total_mbps']/b['total_mean']-1))
    raw=ROOT/'learning_sources/2023A_markdown/A23102470073/A23102470073_raw_layout.md'
    split=re.split(r'## Page (\d+)\n',raw.read_text(encoding='utf-8'))
    pages={int(split[i]):split[i+1] for i in range(1,len(split),2)}
    tables=[]
    for q,nums in [(1,[12,13]),(2,[16]),(3,[27]),(4,[34,35])]:
        pairs=re.findall(r'(?<!\d)(\d{1,2})\s+(\d{8,9})(?!\d)','\n'.join(pages[n] for n in nums))
        indexed={int(k):int(v) for k,v in pairs if 1<=int(k)<=40}
        assert len(indexed)==40,(q,len(indexed))
        values=[indexed[i]/1e6 for i in range(1,41)]
        tables.append(dict(q=q,pages=nums,author_table_mbps=values,mean=statistics.mean(values),sample_sd=statistics.stdev(values),
                           scope='statistics of printed author data, not generated by our simulator'))
    result=dict(scope='full text review; bounded reimplementations and printed-table arithmetic only',
      ablation_design='2x2: extra epoch slot versus extra decrement, five seeds and 100000 epochs per cell; common retry convention r+1 attempts',
      ablations=ablations,q2_exact=q2_exact(),q4_rows=q4rows,author_table_statistics=tables,
      source_sha256={str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest() for p in [raw,Path(__file__),HERE/'q3_state_model.py',CASE/'results/RESULTS.json']})
    (HERE/'REMAINING_RESULTS.json').write_text(json.dumps(result,ensure_ascii=False,indent=2),encoding='utf-8')
    print('Q4 base',q4rows[0]['body'],q4rows[0]['appendix_active'])
    print('Tables',[(t['q'],t['mean'],t['sample_sd']) for t in tables])

if __name__=='__main__':main()
