from pathlib import Path
import json, hashlib
ROOT=Path(__file__).resolve().parents[4]
A=ROOT/'.agents/skills/mathmodel-case-retriever/assets'
checks=[]
def ck(n,c): assert c,n; checks.append(n)
def load(r): return json.loads((ROOT/r).read_text(encoding='utf-8'))
papers=json.loads((A/'papers.json').read_text(encoding='utf-8')); items=papers['papers'] if isinstance(papers,dict) else papers; P={p['paper_id']:p for p in items}
st=load('learning_output/context/learning_state.json')
ck('version',st['current_version']=='1.38.0'); ck('latest S045',st['latest_completed_paper']=='S045'); ck('latest R2',st['reproduction_level_latest']=='S045:R2')
req=['S045_v1.38_训练摘要.md','learning_output/analyses/S045_source_audit.json','learning_output/analyses/S045_result_registry_replay.json',
'knowledge_base/paper_reviews/2025-F-S045-core.json','knowledge_base/candidate_competitions/S045.json','knowledge_base/result_registry/S045.json','knowledge_base/code_cases/2025-F-S045-printed-code-audit.json','knowledge_base/method_modules/2025-F-S045-modules.json','knowledge_base/figure_argumentation/S045.json','knowledge_base/cross_paper_maps/2025-F-S042-S045.json','knowledge_base/figure_decision_rules/2025-F-final.json',
'knowledge_base/error_patterns/sensitivity-ranking-axis-mismatch.json','knowledge_base/error_patterns/posthoc-pairwise-similarity-rewrite.json','knowledge_base/error_patterns/heterogeneous-cosine-without-scaling.json','knowledge_base/error_patterns/route-genetic-operator-feasibility.json','knowledge_base/error_patterns/confidence-vs-distribution-interval-semantic-drift.json',
'learning_output/mini_transfer/2025-F/first_fail.json','learning_output/mini_transfer/2025-F/repaired_pass.json','learning_output/mini_transfer/2025-F/REPORT.md','learning_output/mini_transfer/2025-F/CAPABILITY_EVIDENCE_GATE.md']
for r in req: ck('exists '+r,(ROOT/r).exists() and (ROOT/r).stat().st_size>0)
rv=load('knowledge_base/paper_reviews/2025-F-S045-core.json')
ck('pages94',rv['pages']==94); ck('split train',rv['split']=='train'); ck('R2',rv['reproduction']['level']=='R2'); ck('visual94','94-PAGE' in rv['visual_status']); ck('printed static',any('pp62-94' in x for x in rv['reproduction']['evidence'])); ck('noR3',any('R3:' in x for x in rv['reproduction']['not_achieved']))
ck('paper reviewed94',P['S045']['reviewed_pages']==list(range(1,95))); ck('paper R2',P['S045']['reproduction_level']=='R2'); ck('S045 train',P['S045']['split']=='train')
for pid,n in [('S042',182),('S043',71),('S044',116)]: ck(pid+' preserved',P[pid]['split']=='train' and len(P[pid]['reviewed_pages'])==n)
for pid in ['S013','S014','S015','S016','S030','S031']: ck(pid+' dev unread/reserve',P[pid]['split']=='dev' and P[pid].get('reviewed_pages',[])==[])
# S029 is the only intentionally exposed Dev paper
ck('S029 dev exposed only',P['S029']['split']=='dev' and len(P['S029'].get('reviewed_pages',[]))>0)
for pid in ['S021','S022','S023','S024','S037','S038']: ck(pid+' test frozen',P[pid]['split']=='test' and P[pid].get('reviewed_pages',[])==[])
ck('split sha',hashlib.sha256((A/'split_manifest.json').read_bytes()).hexdigest()=='0f110a9c76f1c8604dbabdee10f9c6cb701e9846755ea9577a3ef59c8318a347')
reg=load('knowledge_base/result_registry/S045.json'); ids={e['id'] for e in reg['entries']}
for x in ['Q1_COST_FORMULA_LENGTH_OMISSION','Q1_FITNESS_OBJECTIVE_DRIFT','Q1_GA_OPERATOR_FEASIBILITY','Q1_PAPER_CODE_OPTIMIZER_COLLAPSE','Q1_SCENIC_PAPER_CODE_DRIFT','Q1_ABSTRACT_OFFICIAL_OVERSTATE','Q2_GMM_MRF_CODE_COLLAPSE','Q2_RANDOM_PLACEHOLDER','Q2_K_SELECTION_DRIFT','Q2_ANCHOR_CIRCULAR','Q2_TABLE66_ARITHMETIC','Q2_SENSITIVITY_RANKING_AXIS_MISMATCH','Q2_INTERVAL_SEMANTICS','Q3_MIXED_SCALE_COSINE','Q3_JACCARD_SEMANTIC_DRIFT','Q3_ALPHA_INTERNAL_SELECTION','Q3_EXTERNAL_VALIDATION_TRUTH_GAP','Q3_CODE_HARDCODED_ADJUSTED_SIM','Q3_SIMILARITY_CODE_MISSING','Q3_EQ713_VISUAL_FORMULA']: ck('reg '+x,x in ids)
rep=load('learning_output/analyses/S045_result_registry_replay.json')['checks']; ck('table66 all',rep['Q2_table66_exact_all_10'] is True); ck('table66 10',len(rep['Q2_table66_calculated'])==10); ck('Jichang100',rep['Q2_table66_calculated']['寄畅园']==100.0); ck('Yiyuan90.8',rep['Q2_table66_calculated']['怡园']==90.8); ck('Zhan88.8',rep['Q2_table66_calculated']['瞻园']==88.8); ck('Shen88.8',rep['Q2_table66_calculated']['沈园']==88.8); ck('Qiyuan36.7',rep['Q2_table66_calculated']['绮园']==36.7); ck('posthoc plus one',rep['Q3_two_adjustments_equal_plus_one'] is True); ck('eq713 visual','abs(' in rep['Q3_eq713_visual']); ck('eq567 no length',rep['Q1_eq567_has_length_term'] is False); ck('sensitivity fail','FAIL' in rep['Q2_sensitivity_axis_contract'])
ca=load('knowledge_base/code_cases/2025-F-S045-printed-code-audit.json'); ck('codeR2',ca['reproduction_level']=='R2'); ck('dijkstra',any('dijkstra_adj' in x for x in ca['Q1']['printed_primitives'])); ck('noGA',any('no printed GA' in x for x in ca['Q1']['missing_or_drift'])); ck('bridge risk',any('straight-line' in x for x in ca['Q1']['missing_or_drift'])); ck('exotic proxy',any('category-count' in x for x in ca['Q1']['missing_or_drift'])); ck('q2 KMeans',any('KMeans' in x for x in ca['Q2']['printed_primitives'])); ck('q2 noMRF',any('no GaussianMixture' in x for x in ca['Q2']['missing_or_drift'])); ck('q2 random',any('np.random.random' in x for x in ca['Q2']['random_or_placeholder'])); ck('q2 axis',any('alpha-scenario' in x for x in ca['Q2']['missing_or_drift'])); ck('q3 hardcoded',len(ca['Q3']['posthoc_output_edit'])>=2); ck('q3 no similarity',any('no implementation' in x for x in ca['Q3']['missing_or_drift']))
mp=load('knowledge_base/cross_paper_maps/2025-F-S042-S045.json'); ck('map final',mp['status']=='FINAL_FOUR_OF_FOUR_TRAIN_PAPERS_REVIEWED'); ck('map all4',mp['papers_reviewed']==['S042','S043','S044','S045']); ck('map none pending',mp['papers_pending']==[]); ck('composer final','method_composer_final' in mp); ck('seven gates',len(mp['method_composer_final']['seven_gate_status'])==7); ck('Q1 final route','recommended_route' in mp['questions']['Q1']); ck('Q2 final route','recommended_route' in mp['questions']['Q2']); ck('Q3 final route','recommended_route' in mp['questions']['Q3'])
fr=load('knowledge_base/figure_decision_rules/2025-F-final.json'); ck('figure final',fr['status']=='FINAL_AFTER_S042_S045'); ck('figure all4',fr['papers_reviewed']==['S042','S043','S044','S045']); ck('figure rules>=10',len(fr['rules'])>=10)
for rel in ['sensitivity-ranking-axis-mismatch.json','posthoc-pairwise-similarity-rewrite.json','heterogeneous-cosine-without-scaling.json','route-genetic-operator-feasibility.json','confidence-vs-distribution-interval-semantic-drift.json']:
 d=load('knowledge_base/error_patterns/'+rel); ck('pattern gate '+rel,bool(d.get('gate')))
summ=load('.agents/skills/mathmodel-case-retriever/assets/core_retrieval_summaries.json'); ck('summary S045','S045' in summ); ck('summary S045 R2',summ['S045']['reproduction_level']=='R2')
cgm=load('.agents/skills/mathmodel-case-retriever/assets/case_group_maps.json'); ck('case final',cgm['2025-F']['status']=='FINAL_FOUR_OF_FOUR_TRAIN_PAPERS_REVIEWED'); ck('case pending none',cgm['2025-F']['pending_papers']==[])
mt1=load('learning_output/mini_transfer/2025-F/first_fail.json'); mt2=load('learning_output/mini_transfer/2025-F/repaired_pass.json'); ck('mini first fail',mt1['status']=='FAIL'); ck('mini invalid A-D',mt1['invalid_edges']==[['A','D']]); ck('mini repaired pass',mt2['status']=='PASS'); ck('mini overall',mt2['overall']=='PASS_MECHANISM_TRANSFER_AFTER_RULE_FIX'); ck('similarity concentration',mt2['similarity_scale_fixture']['raw_both_above_0_999'] is True); ck('similarity scaled separation',mt2['similarity_scale_fixture']['scaled_correct_separation'] is True)
cap=(ROOT/'learning_output/mini_transfer/2025-F/CAPABILITY_EVIDENCE_GATE.md').read_text(encoding='utf-8'); ck('cap no overclaim','NOT ESTABLISHED' in cap); ck('ablation not run','NOT_RUN' in cap)
skill=(ROOT/'.agents/skills/graduate-mathmodel-learning/SKILL.md').read_text(encoding='utf-8'); ck('skill v138','## 21. v1.38 / S045' in skill); ck('skill sensitivity','灵敏度排序必须同一实体轴' in skill); ck('skill cosine','异数量纲 cosine' in skill); ck('skill posthoc','禁止局部事后改相似度' in skill); ck('skill Train complete','32篇 Train 全部 reviewed' in skill)
nexttxt=(ROOT/'learning_output/context/next_learning.md').read_text(encoding='utf-8'); ck('next dev','2024-D' in nexttxt); ck('test frozen text','Test' in nexttxt and 'frozen' in nexttxt); ck('no proxy ablation','proxy' in nexttxt or 'proxies' in nexttxt)
print(f'PASS {len(checks)}/{len(checks)}')
